import { useEffect, useMemo, useState } from 'react';
import api from '../api/client';
import type { RoboCompanion, RoboCompanionStatus, RoboCompanionVisit } from '../api/types';

const pretty=(s:string)=>s.replace(/_/g,' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
const blank={name:'',assetTag:'',model:'',description:'',notes:'',status:'AVAILABLE' as RoboCompanionStatus,active:true};

export default function AdminRoboCompanion(){
 const [robots,setRobots]=useState<RoboCompanion[]>([]);const [visits,setVisits]=useState<RoboCompanionVisit[]>([]);const [filter,setFilter]=useState('ALL');
 const [form,setForm]=useState(blank);const [assignments,setAssignments]=useState<Record<number,number>>({});const [schedules,setSchedules]=useState<Record<number,string>>({});const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=async()=>{try{const [r,v]=await Promise.all([api.get<RoboCompanion[]>('/api/robocompanions'),api.get<RoboCompanionVisit[]>('/api/robocompanion-requests')]);setRobots(r);setVisits(v);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load RoboCompanion operations');}};
 useEffect(()=>{load();},[]);const available=useMemo(()=>robots.filter(r=>r.active&&r.status==='AVAILABLE'),[robots]);const shown=filter==='ALL'?visits:visits.filter(v=>v.status===filter);
 const run=async(work:()=>Promise<unknown>,success:string)=>{try{setError('');await work();setMessage(success);await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}};
 const updateVisit=(id:number,body:object,msg:string)=>run(()=>api.put(`/api/robocompanion-requests/${id}`,body),msg);
 const create=(e:React.FormEvent)=>{e.preventDefault();run(()=>api.post('/api/robocompanions',form),'RoboCompanion created').then(()=>setForm(blank));};
 const save=(r:RoboCompanion)=>run(()=>api.put(`/api/robocompanions/${r.id}`,{name:r.name,assetTag:r.assetTag,model:r.model,description:r.description||'',notes:r.notes||'',status:r.status,active:r.active}),'RoboCompanion updated');
 const setRobot=(index:number,change:Partial<RoboCompanion>)=>setRobots(robots.map((r,i)=>i===index?{...r,...change}:r));
 const complete=(id:number)=>{const note=window.prompt('Completion note:');if(note!==null)updateVisit(id,{status:'COMPLETED',completionNotes:note},'RoboCompanion Visit completed');};
 const reject=(id:number)=>{const note=window.prompt('Reason for rejection (shown to the senior):');if(note!==null)updateVisit(id,{status:'REJECTED',adminNotes:note},'RoboCompanion Visit rejected');};
 return <section className="robo-area">
  <div className="section-heading"><span>Physical robot operations</span><h2>RoboCompanion management</h2></div>{message&&<p className="notice success">{message}</p>}{error&&<p className="notice error">{error}</p>}
  <section className="stat-grid"><article className="stat"><strong>{robots.length}</strong><span>Total RoboCompanions</span></article><article className="stat"><strong>{available.length}</strong><span>Available</span></article><article className="stat"><strong>{robots.filter(r=>r.status==='IN_SERVICE').length}</strong><span>In service</span></article><article className="stat"><strong>{visits.filter(v=>v.status==='REQUESTED').length}</strong><span>Pending requests</span></article><article className="stat"><strong>{visits.filter(v=>['SCHEDULED','ASSIGNED'].includes(v.status)).length}</strong><span>Scheduled visits</span></article></section>
  <form className="card form-grid" onSubmit={create}><div className="full section-heading"><span>Inventory</span><h2>Add a RoboCompanion</h2></div><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Asset tag / serial<input required value={form.assetTag} onChange={e=>setForm({...form,assetTag:e.target.value})}/></label><label>Model<input required value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Initial status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as RoboCompanionStatus})}><option>AVAILABLE</option><option>MAINTENANCE</option></select></label><label className="full">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="full">Internal notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="button full">Add RoboCompanion</button></form>
  <section className="card"><div className="section-heading"><span>Inventory</span><h2>RoboCompanions</h2></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Asset tag</th><th>Model</th><th>Status</th><th>Active</th><th>Notes</th><th></th></tr></thead><tbody>{robots.map((r,i)=><tr key={r.id}><td><input aria-label="Robot name" value={r.name} onChange={e=>setRobot(i,{name:e.target.value})}/></td><td><input aria-label="Asset tag" value={r.assetTag} onChange={e=>setRobot(i,{assetTag:e.target.value})}/></td><td><input aria-label="Robot model" value={r.model} onChange={e=>setRobot(i,{model:e.target.value})}/></td><td><select aria-label="Robot status" value={r.status} disabled={['ASSIGNED','IN_SERVICE','INACTIVE'].includes(r.status)} onChange={e=>setRobot(i,{status:e.target.value as RoboCompanionStatus})}><option>AVAILABLE</option><option>MAINTENANCE</option>{!['AVAILABLE','MAINTENANCE'].includes(r.status)&&<option>{r.status}</option>}</select></td><td><input aria-label="Active" type="checkbox" checked={r.active} disabled={['ASSIGNED','IN_SERVICE'].includes(r.status)} onChange={e=>setRobot(i,{active:e.target.checked,status:e.target.checked&&r.status==='INACTIVE'?'AVAILABLE':r.status})}/></td><td><input aria-label="Robot notes" value={r.notes||''} onChange={e=>setRobot(i,{notes:e.target.value})}/></td><td><button className="button small" onClick={()=>save(r)}>Save</button></td></tr>)}</tbody></table></div></section>
  <div className="toolbar"><label>RoboCompanion request status<select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option>{['REQUESTED','APPROVED','SCHEDULED','ASSIGNED','IN_PROGRESS','COMPLETED','REJECTED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></label></div>
  <section><div className="section-heading"><span>RoboCompanion Visit</span><h2>Visit requests</h2></div><div className="request-grid">{shown.map(v=><article className="card request-card" key={v.id}><div className="assignment-head"><span className={`badge ${v.status.toLowerCase()}`}>{pretty(v.status)}</span><time>{v.requestedDate} {v.requestedTime}</time></div><h3>{v.reason}</h3><p><strong>{v.seniorName}</strong>{v.seniorAddress?` · ${v.seniorAddress}`:''}</p>{v.assistanceNeeds&&<p className="callout">Assistance needs: {v.assistanceNeeds}</p>}{v.serviceNotes&&<p className="muted">Service notes: {v.serviceNotes}</p>}
   {v.status==='REQUESTED'&&<div className="button-row"><button className="button small" onClick={()=>updateVisit(v.id,{status:'APPROVED'},'Request approved')}>Approve</button><button className="button danger small" onClick={()=>reject(v.id)}>Reject</button></div>}
   {v.status==='APPROVED'&&<div className="inline-form"><input type="datetime-local" aria-label="Scheduled time" value={schedules[v.id]||''} onChange={e=>setSchedules({...schedules,[v.id]:e.target.value})}/><button className="button small" disabled={!schedules[v.id]} onClick={()=>updateVisit(v.id,{status:'SCHEDULED',scheduledAt:new Date(schedules[v.id]).toISOString()},'Visit scheduled')}>Schedule</button></div>}
   {v.status==='SCHEDULED'&&<div className="inline-form"><select aria-label="Available RoboCompanion" value={assignments[v.id]||''} onChange={e=>setAssignments({...assignments,[v.id]:Number(e.target.value)})}><option value="">Choose available RoboCompanion</option>{available.map(r=><option key={r.id} value={r.id}>{r.assetTag} · {r.name} ({r.model})</option>)}</select><button className="button small" disabled={!assignments[v.id]} onClick={()=>updateVisit(v.id,{status:'ASSIGNED',assignedRoboCompanionId:assignments[v.id]},'RoboCompanion assigned')}>Assign</button></div>}
   {v.status==='ASSIGNED'&&<button className="button small" onClick={()=>updateVisit(v.id,{status:'IN_PROGRESS'},'Visit started')}>Start service</button>}{v.status==='IN_PROGRESS'&&<button className="button small" onClick={()=>complete(v.id)}>Complete service</button>}
   {v.scheduledAt&&<p className="muted">Scheduled: {new Date(v.scheduledAt).toLocaleString()}</p>}{v.assignedRoboCompanionName&&<p className="muted">Robot: {v.assignedRoboCompanionName} · {v.assignedRoboCompanionAssetTag} ({v.assignedRoboCompanionModel})</p>}{v.adminNotes&&<p className="muted">Admin: {v.adminNotes}</p>}{v.completionNotes&&<p className="muted">Completion: {v.completionNotes}</p>}</article>)}</div></section>
 </section>;
}
