import { useEffect, useMemo, useState } from 'react';
import api from '../api/client';
import { useNavigate } from 'react-router-dom';
import type { CompanionRequest, DashboardSummary, MealRequest, Role, UserRecord } from '../api/types';

const pretty = (value: string) => value.replace(/_/g, ' ').toLowerCase().replace(/^./, (c: string) => c.toUpperCase());

export default function AdminDashboard({ onLogout }: { onLogout: () => void }) {
  const navigate = useNavigate();
  const [summary, setSummary] = useState<DashboardSummary | null>(null); const [users, setUsers] = useState<UserRecord[]>([]); const [meals, setMeals] = useState<MealRequest[]>([]); const [companions, setCompanions] = useState<CompanionRequest[]>([]);
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [section, setSection] = useState<'requests' | 'users'>('requests'); const [filter, setFilter] = useState('ALL');
  const [assignments, setAssignments] = useState<Record<string, number>>({}); const [schedules, setSchedules] = useState<Record<number, string>>({});
  const [newUser, setNewUser] = useState({ email: '', password: '', firstName: '', lastName: '', phone: '', role: 'SENIOR' as Role });
  const volunteers = useMemo(() => users.filter((u) => u.role === 'VOLUNTEER' && u.active), [users]);
  const filteredMeals = filter === 'ALL' ? meals : meals.filter((x) => x.status === filter);
  const filteredCompanions = filter === 'ALL' ? companions : companions.filter((x) => x.status === filter);

  const loadData = async () => { try { const [summaryData, usersData, mealData, companionData] = await Promise.all([api.get<DashboardSummary>('/api/dashboard'), api.get<UserRecord[]>('/api/users'), api.get<MealRequest[]>('/api/meal-requests'), api.get<CompanionRequest[]>('/api/companion-requests')]); setSummary(summaryData); setUsers(usersData); setMeals(mealData); setCompanions(companionData); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load admin data'); } finally { setLoading(false); } };
  useEffect(() => { loadData(); }, []);
  const run = async (work: () => Promise<unknown>, success: string) => { setError(''); try { await work(); setMessage(success); await loadData(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed'); } };
  const updateMeal = (id: number, body: object, success: string) => run(() => api.put(`/api/meal-requests/${id}`, body), success);
  const updateCompanion = (id: number, body: object, success: string) => run(() => api.put(`/api/companion-requests/${id}`, body), success);
  const rejectMeal = (id: number) => { const note = window.prompt('Reason for rejection (shown to the senior):'); if (note !== null) updateMeal(id, { status: 'REJECTED', adminNotes: note }, 'Meal request rejected'); };
  const rejectCompanion = (id: number) => { const note = window.prompt('Reason for rejection (shown to the senior):'); if (note !== null) updateCompanion(id, { status: 'REJECTED', adminNotes: note }, 'Companion request rejected'); };
  const createUser = (e: React.FormEvent) => { e.preventDefault(); run(() => api.post('/api/users', { ...newUser, active: true }), 'User created').then(() => setNewUser({ email: '', password: '', firstName: '', lastName: '', phone: '', role: 'SENIOR' })); };
  const saveUser = (user: UserRecord) => run(() => api.put(`/api/users/${user.id}`, { firstName: user.firstName, lastName: user.lastName, phone: user.phone || '', role: user.role, active: user.active }), 'User updated');
  const deactivate = (user: UserRecord) => { if (user.active && !window.confirm(`Deactivate ${user.firstName} ${user.lastName}?`)) return; run(() => user.active ? api.del(`/api/users/${user.id}`) : api.put(`/api/users/${user.id}`, { active: true }), user.active ? 'User deactivated' : 'User activated'); };

  return <main className="page wide">
    <header className="topbar"><div><span className="eyebrow">Operations</span><h1>Admin dashboard</h1></div><div className="button-row"><button className="button secondary" onClick={() => navigate('/profile')}>Profile</button><button className="button ghost" onClick={onLogout}>Logout</button></div></header>
    {message && <p className="notice success">{message}</p>}{error && <p className="notice error" role="alert">{error}</p>}
    {summary && <section className="stat-grid six"><article className="stat"><strong>{summary.totalUsers}</strong><span>Total users</span></article><article className="stat"><strong>{summary.activeUsers}</strong><span>Active</span></article><article className="stat"><strong>{summary.pendingMealRequests}</strong><span>Pending meals</span></article><article className="stat"><strong>{summary.pendingCompanionRequests}</strong><span>Pending visits</span></article><article className="stat"><strong>{summary.completedDeliveries}</strong><span>Meals delivered</span></article><article className="stat"><strong>{summary.completedCompanions}</strong><span>Visits complete</span></article></section>}
    <nav className="tabs" aria-label="Admin sections"><button className={section === 'requests' ? 'active' : ''} onClick={() => setSection('requests')}>Service requests</button><button className={section === 'users' ? 'active' : ''} onClick={() => setSection('users')}>People & access</button></nav>
    {loading ? <div className="card">Loading operations…</div> : section === 'requests' ? <>
      <div className="toolbar"><label>Status filter<select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="ALL">All statuses</option>{['REQUESTED','APPROVED','SCHEDULED','ASSIGNED','PREPARING','OUT_FOR_DELIVERY','IN_PROGRESS','DELIVERED','COMPLETED','REJECTED','CANCELLED'].map((s) => <option key={s}>{s}</option>)}</select></label></div>
      <section><div className="section-heading"><span>Meal delivery</span><h2>Meal requests</h2></div><div className="request-grid">{filteredMeals.map((meal) => <article className="card request-card" key={meal.id}><div className="assignment-head"><span className={`badge ${meal.status.toLowerCase()}`}>{pretty(meal.status)}</span><time>{meal.requestedDeliveryDate}</time></div><h3>{meal.mealType} × {meal.quantity}</h3><p><strong>{meal.seniorName}</strong> · {meal.deliveryAddress}</p>{meal.dietaryNotes && <p className="callout">Dietary: {meal.dietaryNotes}</p>}{meal.adminNotes && <p className="muted">Admin: {meal.adminNotes}</p>}
        {meal.status === 'REQUESTED' && <div className="button-row"><button className="button small" onClick={() => updateMeal(meal.id, { status: 'APPROVED' }, 'Meal approved')}>Approve</button><button className="button danger small" onClick={() => rejectMeal(meal.id)}>Reject</button></div>}
        {meal.status === 'APPROVED' && <div className="inline-form"><select aria-label="Volunteer" value={assignments[`meal-${meal.id}`] || ''} onChange={(e) => setAssignments({ ...assignments, [`meal-${meal.id}`]: Number(e.target.value) })}><option value="">Choose volunteer</option>{volunteers.map((v) => <option key={v.id} value={v.id}>{v.firstName} {v.lastName}</option>)}</select><button className="button small" disabled={!assignments[`meal-${meal.id}`]} onClick={() => updateMeal(meal.id, { status: 'ASSIGNED', assignedVolunteerId: assignments[`meal-${meal.id}`] }, 'Meal assigned')}>Assign</button></div>}
        {meal.assignedVolunteerName && <p className="muted">Volunteer: {meal.assignedVolunteerName}</p>}</article>)}</div></section>
      <section><div className="section-heading"><span>Companion care</span><h2>Companion requests</h2></div><div className="request-grid">{filteredCompanions.map((item) => <article className="card request-card" key={item.id}><div className="assignment-head"><span className={`badge ${item.status.toLowerCase()}`}>{pretty(item.status)}</span><time>{item.requestedDate} {item.requestedTime}</time></div><h3>{item.reason}</h3><p><strong>{item.seniorName}</strong>{item.seniorAddress ? ` · ${item.seniorAddress}` : ''}</p>{item.serviceNotes && <p className="callout">Service notes: {item.serviceNotes}</p>}
        {item.status === 'REQUESTED' && <div className="button-row"><button className="button small" onClick={() => updateCompanion(item.id, { status: 'APPROVED' }, 'Companion request approved')}>Approve</button><button className="button danger small" onClick={() => rejectCompanion(item.id)}>Reject</button></div>}
        {item.status === 'APPROVED' && <div className="inline-form"><input aria-label="Scheduled date and time" type="datetime-local" value={schedules[item.id] || ''} onChange={(e) => setSchedules({ ...schedules, [item.id]: e.target.value })} /><button className="button small" disabled={!schedules[item.id]} onClick={() => updateCompanion(item.id, { status: 'SCHEDULED', scheduledAt: new Date(schedules[item.id]).toISOString() }, 'Companion service scheduled')}>Schedule</button></div>}
        {item.status === 'SCHEDULED' && <div className="inline-form"><select aria-label="Volunteer" value={assignments[`companion-${item.id}`] || ''} onChange={(e) => setAssignments({ ...assignments, [`companion-${item.id}`]: Number(e.target.value) })}><option value="">Choose volunteer</option>{volunteers.map((v) => <option key={v.id} value={v.id}>{v.firstName} {v.lastName}</option>)}</select><button className="button small" disabled={!assignments[`companion-${item.id}`]} onClick={() => updateCompanion(item.id, { status: 'ASSIGNED', assignedVolunteerId: assignments[`companion-${item.id}`] }, 'Companion service assigned')}>Assign</button></div>}
        {item.scheduledAt && <p className="muted">Scheduled: {new Date(item.scheduledAt).toLocaleString()}</p>}{item.assignedVolunteerName && <p className="muted">Volunteer: {item.assignedVolunteerName}</p>}</article>)}</div></section>
    </> : <>
      <form className="card form-grid" onSubmit={createUser}><div className="full section-heading"><span>Access</span><h2>Create a user</h2></div><label>First name<input required value={newUser.firstName} onChange={(e) => setNewUser({ ...newUser, firstName: e.target.value })} /></label><label>Last name<input required value={newUser.lastName} onChange={(e) => setNewUser({ ...newUser, lastName: e.target.value })} /></label><label>Email<input type="email" required value={newUser.email} onChange={(e) => setNewUser({ ...newUser, email: e.target.value })} /></label><label>Temporary password<input type="password" minLength={8} required value={newUser.password} onChange={(e) => setNewUser({ ...newUser, password: e.target.value })} /></label><label>Phone<input value={newUser.phone} onChange={(e) => setNewUser({ ...newUser, phone: e.target.value })} /></label><label>Role<select value={newUser.role} onChange={(e) => setNewUser({ ...newUser, role: e.target.value as Role })}><option>SENIOR</option><option>VOLUNTEER</option><option>ADMIN</option></select></label><button className="button full">Create user</button></form>
      <section className="card"><div className="section-heading"><span>Directory</span><h2>Manage users</h2></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((user, index) => <tr key={user.id}><td><div className="name-fields"><input aria-label="First name" value={user.firstName} onChange={(e) => setUsers(users.map((u, i) => i === index ? { ...u, firstName: e.target.value } : u))} /><input aria-label="Last name" value={user.lastName} onChange={(e) => setUsers(users.map((u, i) => i === index ? { ...u, lastName: e.target.value } : u))} /></div></td><td>{user.email}</td><td><input aria-label="Phone" value={user.phone || ''} onChange={(e) => setUsers(users.map((u, i) => i === index ? { ...u, phone: e.target.value } : u))} /></td><td><select aria-label="Role" value={user.role} onChange={(e) => setUsers(users.map((u, i) => i === index ? { ...u, role: e.target.value as Role } : u))}><option>SENIOR</option><option>VOLUNTEER</option><option>ADMIN</option></select></td><td>{user.active ? 'Active' : 'Inactive'}</td><td><div className="button-row"><button className="button small" onClick={() => saveUser(user)}>Save</button><button className={`button small ${user.active ? 'danger' : 'secondary'}`} onClick={() => deactivate(user)}>{user.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div></section>
    </>}
  </main>;
}
